# -*- coding: utf-8 -*-
"""Taller 16 Abril.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15vktCKd9C3-uo9b9Q6TGwnl2gkQU_RlH

Ejercicio 1:
"""
### Ejercicio 1

from scipy.optimize import linprog
import math


# Z = 180X1 + 220X2

z = [-180 , -220]


A_ub = [
    [3,4],
    [2 ,1],
    [5,3]
]

b_ub = [120,80,150]

x1_lim = (0, None)
x2_lim = (0, None)

bounds = [x1_lim, x2_lim]

resultado = linprog(z, A_ub=A_ub, b_ub=b_ub, bounds=bounds, method='highs')

print(f"Estado {resultado.message}")
print(f"x1 = {resultado.x[0]}")
print(f"x2 = {resultado.x[1]}")
print(f"Ganancia máxima = {math.fabs(resultado.fun)}")







"""###Ejercicio 2"""

# Valores iniciales (semana 0)
S = 200
M = 80

print(f"{'Semana':<8} {'Sn':>10} {'Mn':>10}")
print("-" * 30)

# Iteramos 50 semanas, suficiente para ver la convergencia
for n in range(50):
    print(f"{n:<8} {S:>10.4f} {M:>10.4f}")

    # Calculamos la siguiente semana con las ecuaciones del modelo
    S_new = 0.6*S + 0.2*M + 40  # S_{n+1}
    M_new = 0.1*S + 0.5*M + 20  # M_{n+1}

    S, M = S_new, M_new

print("-" * 30)
print(f"Valor tras 50 iteraciones: S* = {S:.4f}, M* = {M:.4f}")








"""###Ejercicio 3"""

from scipy.integrate import odeint
import numpy as np

# Parametros
beta = 0.00003
gamma = 0.1
N = 10000

# Definimos la EDO: le decimos a scipy cual es dI/dt
def modelo_SIS(I, t):
    dIdt = beta * (N - I) * I - gamma * I
    return dIdt

# Condicion inicial
I0 = 50

# Vector de tiempo: de 0 a 300 dias
t = np.linspace(0, 300, 300)

# scipy resuelve la EDO automaticamente
I = odeint(modelo_SIS, I0, t)

# Imprimimos resultados
print(f"{'Dia':<8} {'Infectados I(t)':>18} {'Susceptibles S(t)':>20}")
print("-" * 48)
for i in range(len(t)):
    print(f"{t[i]:<8.0f} {I[i][0]:>18.4f} {N - I[i][0]:>20.4f}")

print("-" * 48)
print(f"Equilibrio teorico:  I* = 6666.67,  S* = 3333.33")
print(f"Valor final: I* = {I[-1][0]:.4f}, S* = {N - I[-1][0]:.4f}")







"""###Ejercicio 4

"""

# Parametros
H = 80
K = 1000
r = 0.4
P = 400
años = 100

print(f"{'Año':<8} {'Poblacion P':>15}")
print("-" * 25)

for n in range(años):
    # Imprimimos antes de actualizar
    print(f"{n:<8} {P:>15.4f}")

    # Aplicamos el modelo logistico con pesca
    P = P + r * P * (1 - (P/K)) - H

print("-" * 25)
print(f"Equilibrios teoricos: P* = 723.6 y P* = 276.4")
print(f"Valor tras {años} años: P* = {P:.4f}")
